import type { StoredActivity, StoredGear } from '../services/database';

export const mockGear: StoredGear[] = [
  {
    id: 'b12345',
    primary: true,
    name: 'Trek Domane SL5',
    distance: 5234567,
    brand_name: 'Trek',
    model_name: 'Domane SL5',
    resource_state: 2,
    athleteId: 12345,
  },
  {
    id: 'g67890',
    primary: false,
    name: 'Nike Pegasus 40',
    distance: 823456,
    brand_name: 'Nike',
    model_name: 'Pegasus 40',
    resource_state: 2,
    athleteId: 12345,
  },
  {
    id: 'b11111',
    primary: false,
    name: 'Canyon Grail',
    distance: 1234567,
    brand_name: 'Canyon',
    model_name: 'Grail CF SL',
    resource_state: 2,
    athleteId: 12345,
  },
];

export const mockActivities: StoredActivity[] = [
  {
    id: 1001,
    name: 'Morning Run in Central Park',
    description: 'Beautiful morning run through the park. Perfect weather!',
    distance: 8045.5,
    moving_time: 2400,
    elapsed_time: 2520,
    total_elevation_gain: 45,
    type: 'Run',
    sport_type: 'Run',
    start_date: '2024-01-15T12:30:00Z',
    start_date_local: '2024-01-15T07:30:00Z',
    timezone: '(GMT-05:00) America/New_York',
    utc_offset: -18000,
    location_city: 'New York',
    location_state: 'New York',
    location_country: 'United States',
    achievement_count: 3,
    kudos_count: 15,
    comment_count: 2,
    athlete_count: 1,
    photo_count: 0,
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: 'everyone',
    flagged: false,
    gear_id: 'g67890',
    average_speed: 3.35,
    max_speed: 4.2,
    has_heartrate: true,
    average_heartrate: 152,
    max_heartrate: 175,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    pr_count: 2,
    total_photo_count: 0,
    has_kudoed: false,
    suffer_score: 45,
    calories: 523,
    athleteId: 12345,
    syncedAt: Date.now(),
  },
  {
    id: 1002,
    name: 'Weekend Century Ride',
    description: 'First century of the year! Tough climbs but amazing views.',
    distance: 161234.5,
    moving_time: 18000,
    elapsed_time: 21600,
    total_elevation_gain: 1523,
    type: 'Ride',
    sport_type: 'Ride',
    start_date: '2024-01-14T14:00:00Z',
    start_date_local: '2024-01-14T09:00:00Z',
    timezone: '(GMT-05:00) America/New_York',
    utc_offset: -18000,
    location_city: 'Nyack',
    location_state: 'New York',
    location_country: 'United States',
    achievement_count: 8,
    kudos_count: 42,
    comment_count: 5,
    athlete_count: 3,
    photo_count: 4,
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: 'everyone',
    flagged: false,
    gear_id: 'b12345',
    average_speed: 8.96,
    max_speed: 15.5,
    average_watts: 185,
    weighted_average_watts: 205,
    kilojoules: 3330,
    device_watts: true,
    has_heartrate: true,
    average_heartrate: 145,
    max_heartrate: 178,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    pr_count: 5,
    total_photo_count: 4,
    has_kudoed: false,
    suffer_score: 187,
    calories: 3245,
    athleteId: 12345,
    syncedAt: Date.now(),
  },
  {
    id: 1003,
    name: 'Zwift - Volcano Climb',
    description: undefined,
    distance: 32500,
    moving_time: 3600,
    elapsed_time: 3600,
    total_elevation_gain: 650,
    type: 'VirtualRide',
    sport_type: 'VirtualRide',
    start_date: '2024-01-13T23:00:00Z',
    start_date_local: '2024-01-13T18:00:00Z',
    timezone: '(GMT-05:00) America/New_York',
    utc_offset: -18000,
    achievement_count: 0,
    kudos_count: 5,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    trainer: true,
    commute: false,
    manual: false,
    private: false,
    visibility: 'everyone',
    flagged: false,
    gear_id: 'b12345',
    average_speed: 9.03,
    max_speed: 12.5,
    average_watts: 220,
    weighted_average_watts: 245,
    kilojoules: 792,
    device_watts: true,
    has_heartrate: true,
    average_heartrate: 158,
    max_heartrate: 182,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
    suffer_score: 95,
    calories: 756,
    athleteId: 12345,
    syncedAt: Date.now(),
  },
  {
    id: 1004,
    name: 'Easy Recovery Swim',
    distance: 2000,
    moving_time: 2400,
    elapsed_time: 3000,
    total_elevation_gain: 0,
    type: 'Swim',
    sport_type: 'Swim',
    start_date: '2024-01-12T17:00:00Z',
    start_date_local: '2024-01-12T12:00:00Z',
    timezone: '(GMT-05:00) America/New_York',
    utc_offset: -18000,
    location_city: 'Brooklyn',
    location_state: 'New York',
    location_country: 'United States',
    achievement_count: 0,
    kudos_count: 8,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: 'everyone',
    flagged: false,
    average_speed: 0.83,
    max_speed: 1.2,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
    calories: 450,
    athleteId: 12345,
    syncedAt: Date.now(),
  },
  {
    id: 1005,
    name: 'Trail Hike at Bear Mountain',
    description: 'Great winter hike with amazing views of the Hudson Valley.',
    distance: 12500,
    moving_time: 10800,
    elapsed_time: 14400,
    total_elevation_gain: 520,
    type: 'Hike',
    sport_type: 'Hike',
    start_date: '2024-01-11T15:00:00Z',
    start_date_local: '2024-01-11T10:00:00Z',
    timezone: '(GMT-05:00) America/New_York',
    utc_offset: -18000,
    location_city: 'Bear Mountain',
    location_state: 'New York',
    location_country: 'United States',
    achievement_count: 1,
    kudos_count: 23,
    comment_count: 3,
    athlete_count: 2,
    photo_count: 8,
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: 'everyone',
    flagged: false,
    average_speed: 1.16,
    max_speed: 2.1,
    has_heartrate: true,
    average_heartrate: 125,
    max_heartrate: 155,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    pr_count: 0,
    total_photo_count: 8,
    has_kudoed: false,
    suffer_score: 65,
    calories: 890,
    athleteId: 12345,
    syncedAt: Date.now(),
  },
];

export const mockAthlete = {
  id: 12345,
  username: 'athlete123',
  firstname: 'John',
  lastname: 'Doe',
  city: 'New York',
  state: 'New York',
  country: 'United States',
  profile: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/12345/large.jpg',
  profile_medium: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/12345/medium.jpg',
};
